(load "/home/user/quicklisp/setup.lisp")
(push #p"./" asdf:*central-registry*)
(ql:quickload :fiveam :verbose nil)
(asdf:load-system :opencortex :verbose nil)
(asdf:load-system :opencortex/tests :verbose nil)

(format t "~%=== Running ALL Test Suites ===~%")

(when (find-package :OPENCORTEX-TESTS)
  (fiveam:run! 'OPENCORTEX-TESTS::COMMUNICATION-PROTOCOL-SUITE))
(when (find-package :OPENCORTEX-PIPELINE-TESTS)
  (fiveam:run! 'OPENCORTEX-PIPELINE-TESTS::PIPELINE-SUITE))
(when (find-package :OPENCORTEX-BOOT-TESTS)
  (fiveam:run! 'OPENCORTEX-BOOT-TESTS::BOOT-SUITE))
(when (find-package :OPENCORTEX-MEMORY-TESTS)
  (fiveam:run! 'OPENCORTEX-MEMORY-TESTS::MEMORY-SUITE))
(when (find-package :OPENCORTEX-IMMUNE-SYSTEM-TESTS)
  (fiveam:run! 'OPENCORTEX-IMMUNE-SYSTEM-TESTS::IMMUNE-SUITE))
(when (find-package :OPENCORTEX-EMACS-EDIT-TESTS)
  (fiveam:run! 'OPENCORTEX-EMACS-EDIT-TESTS::EMACS-EDIT-SUITE))
(when (find-package :OPENCORTEX-LISP-UTILS-TESTS)
  (fiveam:run! 'OPENCORTEX-LISP-UTILS-TESTS::LISP-UTILS-SUITE))
(when (find-package :OPENCORTEX-ENGINEERING-STANDARDS-TESTS)
  (fiveam:run! 'OPENCORTEX-ENGINEERING-STANDARDS-TESTS::ENGINEERING-STANDARDS-SUITE))

(format t "~%=== ALL TESTS COMPLETE ===~%")